title: RCH4 Drug
baseURL: /
params:
  base_font: nunito-sans
  palette: blue
  header:
    logo_img_alt: RCH4
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: About RCH4
        url: /about_rch4
        style: link
      - label: RCH4 Clinical Data
        url: /rch4_clinical_data
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
      - label: Faq
        url: /faq
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
      - label: About Us
        url: /about
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
      - label: Contact Us
        url: /contact
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: left
        new_window: false
        no_follow: false
        type: action
  footer:
    sections:
      - type: footer_text
        image_url: /
        image_alt: Footer logo
        title: RCH4 Drug
      - type: footer_nav
        title: Company
        nav_links:
          - label: About Us
            url: /about
            style: link
          - label: Contact Us
            url: /contact
            style: link
      - type: footer_form
        title: Subscribe
        content: Stay up to date with our latest developments.
        form_id: contactForm
        hide_labels: true
        form_fields:
          - input_type: email
            name: email
            label: Email
            default_value: Enter email address
            is_required: true
        submit_label: Subscribe
      - title: lorem-ipsum
        content: >-
          ## Lorem ipsum


          Lorem ipsum dolor sit amet, **consectetur adipiscing elit**, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.


          - Lorem ipsum

          - dolor sit amet
        form_id: lorem-ipsum
        form_action: lorem-ipsum
        hide_labels: false
        form_fields: []
        submit_label: lorem-ipsum
        type: footer_form
    has_nav: false
    nav_links:
      - label: Terms of Service
        url: /terms-of-service
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    content: '&copy; RC Charity. All rights reserved'
  domain: 'https://caring-bee-a536f.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
